AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template to create S3 Bucket

Parameters:
  EnvCode:
    Description: Type of this EnvCode.
    Type: String
  StoreCode:
    Description: Type of this StoreCode.
    Type: String
  Brand:
    Description: Type of this Brand.
    Type: String
  Database:
    Description: Type of this Database.
    Type: String

Resources:
  alltable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Sub ${Database}
      TableInput: 
        Name: !Sub ${Brand}_all_${StoreCode}
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
          skip.header.line.count: 1
          EXTERNAL: 'TRUE'
          has_encrypted_data: 'false'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          NumberOfBuckets: -1
          Columns:
          - Name: 'brand_id'
            Type: string
          - Name: 'brand_name'
            Type: string
          - Name: 'store_id'
            Type: string
          - Name: 'store_name'
            Type: string
          - Name: 'store_name_kn'
            Type: string
          - Name: 'postal_cd'
            Type: string
          - Name: 'city'
            Type: string
          - Name: 'town'
            Type: string
          - Name: 'address'
            Type: string
          - Name: 'building'
            Type: string
          - Name: 'latitude'
            Type: string
          - Name: 'longitude'
            Type: string
          - Name: 'tel'
            Type: string
          - Name: 'opening_hours_1'
            Type: string
          - Name: 'closing_hours_1'
            Type: string
          - Name: 'business_hours_mon_1'
            Type: string
          - Name: 'business_hours_tue_1'
            Type: string
          - Name: 'business_hours_wed_1'
            Type: string
          - Name: 'business_hours_thu_1'
            Type: string
          - Name: 'business_hours_fri_1'
            Type: string
          - Name: 'business_hours_sat_1'
            Type: string
          - Name: 'business_hours_sun_1'
            Type: string
          - Name: 'opening_hours_2'
            Type: string
          - Name: 'closing_hours_2'
            Type: string
          - Name: 'business_hours_mon_2'
            Type: string
          - Name: 'business_hours_tue_2'
            Type: string
          - Name: 'business_hours_wed_2'
            Type: string
          - Name: 'business_hours_thu_2'
            Type: string
          - Name: 'business_hours_fri_2'
            Type: string
          - Name: 'business_hours_sat_2'
            Type: string
          - Name: 'business_hours_sun_2'
            Type: string
          - Name: 'regular_holiday'
            Type: string
          - Name: 'url'
            Type: string
          - Name: 'map_optout'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/brand/${Brand}/all/
          SerdeInfo:
            Parameters:
              integerization.format: ","
              quoteChar: '"'
              escapeChar: '\'
              field.delim: ','
              serialization.format: '1'
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
  difftable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Sub ${Database}
      TableInput: 
        Name: !Sub ${Brand}_diff_${StoreCode}
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
          skip.header.line.count: 1
          EXTERNAL: 'TRUE'
          has_encrypted_data: 'false'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          NumberOfBuckets: -1
          Columns:
          - Name: 'brand_id'
            Type: string
          - Name: 'brand_name'
            Type: string
          - Name: 'store_id'
            Type: string
          - Name: 'store_name'
            Type: string
          - Name: 'store_name_kn'
            Type: string
          - Name: 'postal_cd'
            Type: string
          - Name: 'city'
            Type: string
          - Name: 'town'
            Type: string
          - Name: 'address'
            Type: string
          - Name: 'building'
            Type: string
          - Name: 'latitude'
            Type: string
          - Name: 'longitude'
            Type: string
          - Name: 'tel'
            Type: string
          - Name: 'opening_hours_1'
            Type: string
          - Name: 'closing_hours_1'
            Type: string
          - Name: 'business_hours_mon_1'
            Type: string
          - Name: 'business_hours_tue_1'
            Type: string
          - Name: 'business_hours_wed_1'
            Type: string
          - Name: 'business_hours_thu_1'
            Type: string
          - Name: 'business_hours_fri_1'
            Type: string
          - Name: 'business_hours_sat_1'
            Type: string
          - Name: 'business_hours_sun_1'
            Type: string
          - Name: 'opening_hours_2'
            Type: string
          - Name: 'closing_hours_2'
            Type: string
          - Name: 'business_hours_mon_2'
            Type: string
          - Name: 'business_hours_tue_2'
            Type: string
          - Name: 'business_hours_wed_2'
            Type: string
          - Name: 'business_hours_thu_2'
            Type: string
          - Name: 'business_hours_fri_2'
            Type: string
          - Name: 'business_hours_sat_2'
            Type: string
          - Name: 'business_hours_sun_2'
            Type: string
          - Name: 'regular_holiday'
            Type: string
          - Name: 'url'
            Type: string
          - Name: 'map_optout'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/brand/${Brand}/diff/
          SerdeInfo:
            Parameters:
              integerization.format: ","
              quoteChar: '"'
              escapeChar: '\'
              field.delim: ','
              serialization.format: '1'
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
  temptable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Sub ${Database}
      TableInput: 
        Name: !Sub ${Brand}_temp_${StoreCode}
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
          skip.header.line.count: 1
          EXTERNAL: 'TRUE'
          has_encrypted_data: 'false'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          NumberOfBuckets: -1
          Columns:
          - Name: 'brand_id'
            Type: string
          - Name: 'brand_name'
            Type: string
          - Name: 'store_id'
            Type: string
          - Name: 'store_name'
            Type: string
          - Name: 'store_name_kn'
            Type: string
          - Name: 'postal_cd'
            Type: string
          - Name: 'city'
            Type: string
          - Name: 'town'
            Type: string
          - Name: 'address'
            Type: string
          - Name: 'building'
            Type: string
          - Name: 'latitude'
            Type: string
          - Name: 'longitude'
            Type: string
          - Name: 'tel'
            Type: string
          - Name: 'opening_hours_1'
            Type: string
          - Name: 'closing_hours_1'
            Type: string
          - Name: 'business_hours_mon_1'
            Type: string
          - Name: 'business_hours_tue_1'
            Type: string
          - Name: 'business_hours_wed_1'
            Type: string
          - Name: 'business_hours_thu_1'
            Type: string
          - Name: 'business_hours_fri_1'
            Type: string
          - Name: 'business_hours_sat_1'
            Type: string
          - Name: 'business_hours_sun_1'
            Type: string
          - Name: 'opening_hours_2'
            Type: string
          - Name: 'closing_hours_2'
            Type: string
          - Name: 'business_hours_mon_2'
            Type: string
          - Name: 'business_hours_tue_2'
            Type: string
          - Name: 'business_hours_wed_2'
            Type: string
          - Name: 'business_hours_thu_2'
            Type: string
          - Name: 'business_hours_fri_2'
            Type: string
          - Name: 'business_hours_sat_2'
            Type: string
          - Name: 'business_hours_sun_2'
            Type: string
          - Name: 'regular_holiday'
            Type: string
          - Name: 'url'
            Type: string
          - Name: 'map_optout'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/brand/${Brand}/temp/
          SerdeInfo:
            Parameters:
              integerization.format: ","
              quoteChar: '"'
              escapeChar: '\'
              field.delim: ','
              serialization.format: '1'
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde

Outputs:
  CreateResult:
    Value: !Sub ${Brand}_all_${StoreCode}
    Value: !Sub ${Brand}_diff_${StoreCode}
    Value: !Sub ${Brand}_temp_${StoreCode}
