AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template to create S3 Bucket

Parameters:
  EnvCode:
    Description: Type of this EnvCode.
    Type: String
  StoreCode:
    Description: Type of this StoreCode.
    Type: String
  Brand:
    Description: Type of this Brand.
    Type: String
  Database:
    Description: Type of this Database.
    Type: String

Resources:
  alltable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Sub ${Database}
      TableInput: 
        Name: !Sub ${Brand}_all_${StoreCode}
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
          skip.header.line.count: 1
          EXTERNAL: 'TRUE'
          has_encrypted_data: 'false'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          NumberOfBuckets: -1
          Columns:
          - Name: 'column name'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/brand/${Brand}/all/
          SerdeInfo:
            Parameters:
              integerization.format: ","
              quoteChar: '"'
              escapeChar: '\'
              field.delim: ','
              serialization.format: '1'
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
  difftable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Sub ${Database}
      TableInput: 
        Name: !Sub ${Brand}_diff_${StoreCode}
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
          skip.header.line.count: 1
          EXTERNAL: 'TRUE'
          has_encrypted_data: 'false'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          NumberOfBuckets: -1
          Columns:
          - Name: 'column name'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/brand/${Brand}/diff/
          SerdeInfo:
            Parameters:
              integerization.format: ","
              quoteChar: '"'
              escapeChar: '\'
              field.delim: ','
              serialization.format: '1'
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
  temptable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Sub ${Database}
      TableInput: 
        Name: !Sub ${Brand}_temp_${StoreCode}
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
          skip.header.line.count: 1
          EXTERNAL: 'TRUE'
          has_encrypted_data: 'false'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          NumberOfBuckets: -1
          Columns:
          - Name: 'column name'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/brand/${Brand}/temp/
          SerdeInfo:
            Parameters:
              integerization.format: ","
              quoteChar: '"'
              escapeChar: '\'
              field.delim: ','
              serialization.format: '1'
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
