AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template to create S3 Bucket

Parameters:
  EnvCode:
    Description: Type of this BranchCode.
    Type: String
  StoreCode:
    Description: Type of this StoreCode.
    Type: String
  Database:
    Description: Type of this Database.
    Type: String

Resources:
  storebucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${EnvCode}.${StoreCode}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
  uploadtable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: ${Database}
      TableInput: 
        Name: !Sub store_mst_${StoreCode}
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
            - Name: 'id'
              Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/upload/
          SerdeInfo:
            Parameters:
              quotechar: '\"'
              skip.header.line.count: 1
              escapechar: '\\'
              EXTERNAL: 'TRUE'
              field.delim: ','
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde

Outputs:
  CreateResult:
    Value: !Sub ${EnvCode}-${StoreCode}-bucket
    Value: !Sub ${EnvCode}_${StoreCode}_upload_table
