AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template to create S3 Bucket

Parameters:
  StoreCode:
    Description: Type of this StoreCode.
    Type: String
  BranchCode:
    Description: Type of this BacketName.
    Type: String

Resources:
  alltable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: tpp_db
      TableInput: 
        Name: !Sub ${StoreCode}_${BranchCode}_*brand*_all
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
          - Name: 'column name'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${StoreCode}-${BranchCode}/brand/*brand*/all/
          SerdeInfo:
            Parameters:
              quotechar: '"'
              skip.header.line.count: 1
              EXTERNAL: 'TRUE'
              field.delim: ','
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
  difftable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: tpp_db
      TableInput: 
        Name: !Sub ${StoreCode}_${BranchCode}_*brand*_diff
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
          - Name: 'column name'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${StoreCode}-${BranchCode}/brand/*brand*/diff/
          SerdeInfo:
            Parameters:
              quotechar: '"'
              skip.header.line.count: 1
              EXTERNAL: 'TRUE'
              field.delim: ','
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
  temptable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: tpp_db
      TableInput: 
        Name: !Sub ${StoreCode}_${BranchCode}_*brand*_temp
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
          - Name: 'column name'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${StoreCode}-${BranchCode}/brand/*brand*/temp/
          SerdeInfo:
            Parameters:
              quotechar: '"'
              skip.header.line.count: 1
              EXTERNAL: 'TRUE'
              field.delim: ','
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde

Outputs:
  CreateResult:
    Value: !Sub ${StoreCode}_${BranchCode}_*brand*_all
    Value: !Sub ${StoreCode}_${BranchCode}_*brand*_diff
    Value: !Sub ${StoreCode}_${BranchCode}_*brand*_temp

