AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template to create S3 Bucket

Parameters:
  EnvCode:
    Description: Type of this EnvCode.
    Type: String
  StoreCode:
    Description: Type of this StoreCode.
    Type: String

Resources:
  alltable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: tpp_db
      TableInput: 
        Name: !Sub ${EnvCode}_${StoreCode}_paypay_all
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
          - Name: 'brand_id'
            Type: string
          - Name: 'brand_name'
            Type: string
          - Name: 'store_id'
            Type: string
          - Name: 'store_name'
            Type: string
          - Name: 'store_name_kn'
            Type: string
          - Name: 'postal_cd'
            Type: string
          - Name: 'city'
            Type: string
          - Name: 'town'
            Type: string
          - Name: 'address'
            Type: string
          - Name: 'building'
            Type: string
          - Name: 'latitude'
            Type: string
          - Name: 'longitude'
            Type: string
          - Name: 'tel'
            Type: string
          - Name: 'opening_hours_1'
            Type: string
          - Name: 'closing_hours_1'
            Type: string
          - Name: 'business_hours_mon_1'
            Type: string
          - Name: 'business_hours_tue_1'
            Type: string
          - Name: 'business_hours_wed_1'
            Type: string
          - Name: 'business_hours_thu_1'
            Type: string
          - Name: 'business_hours_fri_1'
            Type: string
          - Name: 'business_hours_sat_1'
            Type: string
          - Name: 'business_hours_sun_1'
            Type: string
          - Name: 'opening_hours_2'
            Type: string
          - Name: 'closing_hours_2'
            Type: string
          - Name: 'business_hours_mon_2'
            Type: string
          - Name: 'business_hours_tue_2'
            Type: string
          - Name: 'business_hours_wed_2'
            Type: string
          - Name: 'business_hours_thu_2'
            Type: string
          - Name: 'business_hours_fri_2'
            Type: string
          - Name: 'business_hours_sat_2'
            Type: string
          - Name: 'business_hours_sun_2'
            Type: string
          - Name: 'regular_holiday'
            Type: string
          - Name: 'url'
            Type: string
          - Name: 'map_optout'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/brand/paypay/all/
          SerdeInfo:
            Parameters:
              quotechar: '"'
              skip.header.line.count: 1
              EXTERNAL: 'TRUE'
              field.delim: ','
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
  difftable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: tpp_db
      TableInput: 
        Name: !Sub ${EnvCode}_${StoreCode}_paypay_diff
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
          - Name: 'brand_id'
            Type: string
          - Name: 'brand_name'
            Type: string
          - Name: 'store_id'
            Type: string
          - Name: 'store_name'
            Type: string
          - Name: 'store_name_kn'
            Type: string
          - Name: 'postal_cd'
            Type: string
          - Name: 'city'
            Type: string
          - Name: 'town'
            Type: string
          - Name: 'address'
            Type: string
          - Name: 'building'
            Type: string
          - Name: 'latitude'
            Type: string
          - Name: 'longitude'
            Type: string
          - Name: 'tel'
            Type: string
          - Name: 'opening_hours_1'
            Type: string
          - Name: 'closing_hours_1'
            Type: string
          - Name: 'business_hours_mon_1'
            Type: string
          - Name: 'business_hours_tue_1'
            Type: string
          - Name: 'business_hours_wed_1'
            Type: string
          - Name: 'business_hours_thu_1'
            Type: string
          - Name: 'business_hours_fri_1'
            Type: string
          - Name: 'business_hours_sat_1'
            Type: string
          - Name: 'business_hours_sun_1'
            Type: string
          - Name: 'opening_hours_2'
            Type: string
          - Name: 'closing_hours_2'
            Type: string
          - Name: 'business_hours_mon_2'
            Type: string
          - Name: 'business_hours_tue_2'
            Type: string
          - Name: 'business_hours_wed_2'
            Type: string
          - Name: 'business_hours_thu_2'
            Type: string
          - Name: 'business_hours_fri_2'
            Type: string
          - Name: 'business_hours_sat_2'
            Type: string
          - Name: 'business_hours_sun_2'
            Type: string
          - Name: 'regular_holiday'
            Type: string
          - Name: 'url'
            Type: string
          - Name: 'map_optout'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/brand/paypay/diff/
          SerdeInfo:
            Parameters:
              quotechar: '"'
              skip.header.line.count: 1
              EXTERNAL: 'TRUE'
              field.delim: ','
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde
  temptable:
    Type: AWS::Glue::Table
    DeletionPolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: tpp_db
      TableInput: 
        Name: !Sub ${EnvCode}_${StoreCode}_paypay_temp
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: 'csv'
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          Columns:
          - Name: 'brand_id'
            Type: string
          - Name: 'brand_name'
            Type: string
          - Name: 'store_id'
            Type: string
          - Name: 'store_name'
            Type: string
          - Name: 'store_name_kn'
            Type: string
          - Name: 'postal_cd'
            Type: string
          - Name: 'city'
            Type: string
          - Name: 'town'
            Type: string
          - Name: 'address'
            Type: string
          - Name: 'building'
            Type: string
          - Name: 'latitude'
            Type: string
          - Name: 'longitude'
            Type: string
          - Name: 'tel'
            Type: string
          - Name: 'opening_hours_1'
            Type: string
          - Name: 'closing_hours_1'
            Type: string
          - Name: 'business_hours_mon_1'
            Type: string
          - Name: 'business_hours_tue_1'
            Type: string
          - Name: 'business_hours_wed_1'
            Type: string
          - Name: 'business_hours_thu_1'
            Type: string
          - Name: 'business_hours_fri_1'
            Type: string
          - Name: 'business_hours_sat_1'
            Type: string
          - Name: 'business_hours_sun_1'
            Type: string
          - Name: 'opening_hours_2'
            Type: string
          - Name: 'closing_hours_2'
            Type: string
          - Name: 'business_hours_mon_2'
            Type: string
          - Name: 'business_hours_tue_2'
            Type: string
          - Name: 'business_hours_wed_2'
            Type: string
          - Name: 'business_hours_thu_2'
            Type: string
          - Name: 'business_hours_fri_2'
            Type: string
          - Name: 'business_hours_sat_2'
            Type: string
          - Name: 'business_hours_sun_2'
            Type: string
          - Name: 'regular_holiday'
            Type: string
          - Name: 'url'
            Type: string
          - Name: 'map_optout'
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${EnvCode}.${StoreCode}/brand/paypay/temp/
          SerdeInfo:
            Parameters:
              quotechar: '"'
              skip.header.line.count: 1
              EXTERNAL: 'TRUE'
              field.delim: ','
            SerializationLibrary: org.apache.hadoop.hive.serde2.OpenCSVSerde

Outputs:
  CreateResult:
    Value: !Sub ${EnvCode}_${StoreCode}_paypay_all
    Value: !Sub ${EnvCode}_${StoreCode}_paypay_diff
    Value: !Sub ${EnvCode}_${StoreCode}_paypay_temp

